/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.TelaViewController;
import Model.Administrador;
import java.awt.Color;
import Model.Produto;
import Service.ADMService;
import Service.ProdutoService;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rapha
 */
public class TelaRelatorio extends javax.swing.JFrame {

    /**
     * Creates new form AdmView
     */
    public TelaRelatorio() {
        initComponents();

        DefaultTableCellRenderer head_render = new DefaultTableCellRenderer();
        head_render.setBackground(new Color(254,254,254));
        tabela.getTableHeader().setDefaultRenderer(head_render);
        head_render.setOpaque(true);
        
        atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddADM = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        AddADM_labelNome = new javax.swing.JLabel();
        AddADM_labelNomeDeUsuario = new javax.swing.JLabel();
        AddADM_labelSenha = new javax.swing.JLabel();
        AddADM_labelIdade = new javax.swing.JLabel();
        AddADM_labelDepartamento = new javax.swing.JLabel();
        AddADM_labelFuncionarios = new javax.swing.JLabel();
        AddADM_CampoDeTexto_Nome = new javax.swing.JTextField();
        AddADM_CampoDeTexto_NomeDeUsuario = new javax.swing.JTextField();
        AddADM_CampoDeTexto_Senha = new javax.swing.JTextField();
        AddADM_CampoDeTexto_Idade = new javax.swing.JTextField();
        AddADM_CampoDeTexto_Departamento = new javax.swing.JTextField();
        AddADM_CampoDeTexto_Funcionarios = new javax.swing.JTextField();
        AddADM_botaoAdicionar = new javax.swing.JButton();
        DelADM = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        labelRemoveAdministradorbyID = new javax.swing.JLabel();
        DelADM_labelID = new javax.swing.JLabel();
        DelADM_CampoDeTexto_ID = new javax.swing.JTextField();
        DelADM_botaoRemover = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        jPanel2.setBackground(new java.awt.Color(180, 142, 243));

        AddADM_labelNome.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        AddADM_labelNome.setText("Nome");

        AddADM_labelNomeDeUsuario.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        AddADM_labelNomeDeUsuario.setText("Nome De Usuário");

        AddADM_labelSenha.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        AddADM_labelSenha.setText("Senha");

        AddADM_labelIdade.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        AddADM_labelIdade.setText("Idade");

        AddADM_labelDepartamento.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        AddADM_labelDepartamento.setText("Departamento");

        AddADM_labelFuncionarios.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        AddADM_labelFuncionarios.setText("Funcionários");

        AddADM_botaoAdicionar.setText("Adicionar");
        AddADM_botaoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddADM_botaoAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AddADM_labelFuncionarios)
                            .addComponent(AddADM_labelDepartamento)
                            .addComponent(AddADM_labelIdade)
                            .addComponent(AddADM_labelSenha)
                            .addComponent(AddADM_labelNomeDeUsuario)
                            .addComponent(AddADM_labelNome)
                            .addComponent(AddADM_CampoDeTexto_Nome, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                            .addComponent(AddADM_CampoDeTexto_NomeDeUsuario)
                            .addComponent(AddADM_CampoDeTexto_Senha)
                            .addComponent(AddADM_CampoDeTexto_Idade)
                            .addComponent(AddADM_CampoDeTexto_Departamento)
                            .addComponent(AddADM_CampoDeTexto_Funcionarios)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(AddADM_botaoAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(AddADM_labelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddADM_CampoDeTexto_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddADM_labelNomeDeUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddADM_CampoDeTexto_NomeDeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddADM_labelSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddADM_CampoDeTexto_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddADM_labelIdade)
                .addGap(12, 12, 12)
                .addComponent(AddADM_CampoDeTexto_Idade, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddADM_labelDepartamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddADM_CampoDeTexto_Departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddADM_labelFuncionarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddADM_CampoDeTexto_Funcionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AddADM_botaoAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout AddADMLayout = new javax.swing.GroupLayout(AddADM.getContentPane());
        AddADM.getContentPane().setLayout(AddADMLayout);
        AddADMLayout.setHorizontalGroup(
            AddADMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AddADMLayout.setVerticalGroup(
            AddADMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(180, 142, 243));

        labelRemoveAdministradorbyID.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelRemoveAdministradorbyID.setText("Remover ADM por ID");

        DelADM_labelID.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        DelADM_labelID.setText("Digite o ID do ADM");

        DelADM_botaoRemover.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DelADM_botaoRemover.setText("REMOVER");
        DelADM_botaoRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelADM_botaoRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(DelADM_labelID))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(labelRemoveAdministradorbyID))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(DelADM_CampoDeTexto_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(DelADM_botaoRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelRemoveAdministradorbyID)
                .addGap(55, 55, 55)
                .addComponent(DelADM_labelID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DelADM_CampoDeTexto_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(DelADM_botaoRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout DelADMLayout = new javax.swing.GroupLayout(DelADM.getContentPane());
        DelADM.getContentPane().setLayout(DelADMLayout);
        DelADMLayout.setHorizontalGroup(
            DelADMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DelADMLayout.setVerticalGroup(
            DelADMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(180, 142, 243));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "ID Vendedor", "Preço total", "Data de venda", "ID Cliente", "Forma de PGTO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.setShowGrid(true);
        jScrollPane1.setViewportView(tabela);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1133, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddADM_botaoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddADM_botaoAdicionarActionPerformed
         Administrador administrador = new Administrador();
        TelaViewController telaViewController = new TelaViewController();
        
        administrador.setNome(String.valueOf(AddADM_CampoDeTexto_Nome.getText()));
        administrador.setNomeDeUsuario(String.valueOf(AddADM_CampoDeTexto_NomeDeUsuario.getText()));
        administrador.setSenha(String.valueOf(AddADM_CampoDeTexto_Senha.getText()));
        administrador.setIdade(Integer.valueOf(AddADM_CampoDeTexto_Idade.getText()));
        administrador.setDepartamento(String.valueOf(AddADM_CampoDeTexto_Departamento.getText()));
        administrador.setFuncionarios(Integer.valueOf(AddADM_CampoDeTexto_Funcionarios.getText()));
        
        if (telaViewController.validarDados(administrador) == true) {
            if (telaViewController.adicionarAdministrador(administrador) == true) {
                JOptionPane.showMessageDialog(null, "Funcionario adicionado com sucesso", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
                atualizarTabela();
                AddADM.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, telaViewController.getCodigoDeErro(), "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, telaViewController.getCodigoDeErro(), "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_AddADM_botaoAdicionarActionPerformed

    private void DelADM_botaoRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelADM_botaoRemoverActionPerformed
        TelaViewController telaViewController = new TelaViewController();
        
        if (telaViewController.apagarAdministrador(Integer.valueOf(DelADM_CampoDeTexto_ID.getText())) == true) {
            JOptionPane.showMessageDialog(null, "Funcionario apagado com sucesso", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
            atualizarTabela();
            DelADM.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, telaViewController.getCodigoDeErro(), "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_DelADM_botaoRemoverActionPerformed
    
    private void atualizarTabela() {
        TelaViewController telaViewController = new TelaViewController();
        List<Administrador> administradores = new ArrayList(telaViewController.listarAdministrador());
        int n = administradores.size();
        DefaultTableModel dfm = (DefaultTableModel) tabela.getModel();
        
        dfm.removeRow(0);
        for (int i = 0; i < dfm.getRowCount(); i++) {
            dfm.removeRow(i);
        }
        
        for (int i = 0; i < n; i++) {
            Administrador administrador = (Administrador) administradores.get(i);
            dfm.insertRow(i, telaViewController.getDadosToTabelaADM(administrador));
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame AddADM;
    private javax.swing.JTextField AddADM_CampoDeTexto_Departamento;
    private javax.swing.JTextField AddADM_CampoDeTexto_Funcionarios;
    private javax.swing.JTextField AddADM_CampoDeTexto_Idade;
    private javax.swing.JTextField AddADM_CampoDeTexto_Nome;
    private javax.swing.JTextField AddADM_CampoDeTexto_NomeDeUsuario;
    private javax.swing.JTextField AddADM_CampoDeTexto_Senha;
    private javax.swing.JButton AddADM_botaoAdicionar;
    private javax.swing.JLabel AddADM_labelDepartamento;
    private javax.swing.JLabel AddADM_labelFuncionarios;
    private javax.swing.JLabel AddADM_labelIdade;
    private javax.swing.JLabel AddADM_labelNome;
    private javax.swing.JLabel AddADM_labelNomeDeUsuario;
    private javax.swing.JLabel AddADM_labelSenha;
    private javax.swing.JFrame DelADM;
    private javax.swing.JTextField DelADM_CampoDeTexto_ID;
    private javax.swing.JButton DelADM_botaoRemover;
    private javax.swing.JLabel DelADM_labelID;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelRemoveAdministradorbyID;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables

    void isVisible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
